name = "mini"
license = "MIT"
licenselink = "https://github.com/soryu-ryouji/hugo-mini/main/LICENSE"
description = "A minimalism theme"
homepage = "https://github.com/soryu-ryouji/hugo-mini"
tags = ["blog", "minimalist"]
features = []
min_version = "0.41.0"

[author]
  name = "soryu-ryouji"
  homepage = "soryu-ryouji.cc"
